Task1/selection.py.txt
=> Selction Sort

Task1/Ahmed Zakaria Ahmed Elrefay
size = len(arr)
for i in range(size):
min_index = i
for j in range(i + 1, size):
min_index = j
num = int(input("Enter the value of num: "))
array = []
print("Enter the elements one by one:")
for _ in range(num):
element = int(input())
array.append(element)
selection_sort(array)
print("Sorted array is:")
for element in array:
print(element)
=> Create Ahmed Zakaria Ahmed Elrefay

Task1/هبه الله ابراهيم عبد الله ابراهيم
=> Create هبه الله ابراهيم عبد الله ابراهيم

Task1/Ahmed Mahmoud Ahmed
min_idx = i
if arr[j] < arr[min_idx]:
min_idx = j
arr[i], arr[min_idx] = arr[min_idx], arr[i]
print(f"Step {i+1}: {arr}")
print(arr)
selection_sort(arr)
print(arr)
=> Create Ahmed Mahmoud Ahmed

Task1/Somaya Mostafa Mahmoud
=> Create Somaya Mostafa Mahmoud

Task1/Omar Abdullah Ahmed.py
=> Create Omar Abdullah Ahmed.py

Task1/Omar Abdullah Ahmed.py
=> Omar Abdullah Ahmed.py

Task1/Moustafa Mahmoud Abd El Azeem
#section 1
def selectionsort(arr):
n = len(arr)
for i in range(n):
min_index = i
print(f"Step {i + 1}: Current array: {arr}")
for j in range(i + 1, n):
min_index = j
print(f"Swapping {arr[min_index]} and {arr[i]}")
print(f"Array after step {i + 1}: {arr}\n")
arr = [33, 20, 10, 18, 9]
selectionsort(arr)
=> Create Moustafa Mahmoud Abd El Azeem

Ahmed Osama Salah
min_index = i
for j in range(i + 1, len(arr)):
min_index = j
my_num = [64, 25, 12, 22, 11]
selection_sort(my_num)
print("orederd list :", my_num)
=> Create Ahmed Osama Salah

Mahmoud Mostafa Mahmoud  Badr
size = len(arr)
for i in range(size):
min_index = i
for j in range(i + 1, size):
min_index = j
num = int(input("Enter the value of num: "))
array = []
print("Enter the elements one by one:")
for _ in range(num):
element = int(input())
array.append(element)
selection_sort(array)
print("Sorted array is:")
for element in array:
print(element)
=> Create Mahmoud Mostafa Mahmoud  Badr

Task1/Mouner Saleh
=> Create Mouner Saleh

Ahmed Hassan Elsaid Zaki
size = len(arr)
for i in range(size):
min_index = i
for j in range(i + 1, size):
min_index = j
num = int(input("Enter the value of num: "))
array = []
print("Enter the elements one by one:")
for _ in range(num):
element = int(input())
array.append(element)
selection_sort(array)
print("Sorted array is:")
for element in array:
print(element)
=> Create Ahmed Hassan  elsaid  zaki

نورهان حسين احمد فتوح الغرباوي
=> Update نورهان حسين احمد فتوح الغرباوي

shahd samir abdelazim anbar
=> Create shahd samir abdelazim anbar

Task1/haneen mohamed abo el-majd
=> Create haneen mohamed abo el-majd

Mohammed Mahmoud Mahmoud Eldakroury.py
=> Mohammed Eldakroury (insertion sort alg).py

Task1/Eslam Elsayed Eltabie
def selection_sort(arr):    # arr -> name of array
min_index = i
min_index = j
return arr
sorted_arr = selection_sort(arr)
print("Sorted array:", sorted_arr)
=> Create Eslam Elsayed Eltabie

Task1/Ahmed Ashraf Ahmed Akl
def selection_sort(arr):    # arr -> name of array
min_index = i
min_index = j
return arr
sorted_arr = selection_sort(arr)
print("Sorted array:", sorted_arr)
=> Create Ahmed Ashraf Ahmed Akl

Task1/Rwan taha
#rwan taha kassem
#sec 4
min = i
if arr[j] < arr[min]:
min = j
arr[i], arr[min] = arr[min], arr[i]
print(arr)
arr = [52, 18, 2, 67, 3, 0]
selection_sort(arr)
print("sorted array is:", arr)
=>  Rwan taha

Task1/Kaareem Mohamed Ramadan Ali
def selection_sort(arr):   
min_index = i
min_index = j
return arr
sorted_arr = selection_sort(arr)
print("Sorted array is:", sorted_arr)
=> Create Kaareem Mohamed Ramadan Ali

Hassan Elsayed Hassan Bassiouni
n = len(arr)
for i in range(n):
min_index = i
for j in range(i+1, n):
min_index = j
print("Original array:", arr)
selection_sort(arr)
print("Sorted array:", arr)
=> Create Hassan Elsayed Hassan Bassiouni

Task1/Doha Abdelrazek
def selection(arr):
index = i
if arr[j] < arr[index]:
index = j
arr[i], arr[index] = arr[index], arr[i]
arr = [77,9,33,5,18]
selection(arr)
print( arr)
=> Doha Abdelrazek

Task1/Asmaa Gamal
=> Create Asmaa Gamal

Task2/khaled elnabawy
import itertools
import numpy as np
conflict_table = [
{'sub_id': 100, 'Conflict_sub_id': 200, 'NumOfInterection': 30},
{'sub_id': 100, 'Conflict_sub_id': 300, 'NumOfInterection': 15},
{'sub_id': 200, 'Conflict_sub_id': 300, 'NumOfInterection': 20}
]
subject_levels = [
{'sub_id': 100, 'level': 1},
{'sub_id': 200, 'level': 2},
{'sub_id': 300, 'level': 3}
]
subjects_per_level = 6
def calculate_final_cost(schedule, conflict_table):
cost = 0
for conflict in conflict_table:
sub1_position = schedule.index(conflict['sub_id'])
sub2_position = schedule.index(conflict['Conflict_sub_id'])
if abs(sub1_position - sub2_position) <= 1:  
cost += conflict['NumOfInterection']
return cost
def divide_subjects_by_levels(subject_levels):
levels = {}
for subject in subject_levels:
level = subject['level']
if …
=> Create khaled elnabawy

Task2/Ahmed Ashraf Mohamed.py
=> Create Ahmed Ashraf Mohamed.py

Task2/Ahmed Ashraf Lebshten.py
=> Create Ahmed Ashraf Lebshten.py

Task2/Ahmed Zakaria El-Refay
import itertools
def parse_input(conflicts, levels, subjects_per_level):
conflict_dict = {}
for sub_id, conflict_sub_id, num_of_intersections in conflicts:
conflict_dict[(sub_id, conflict_sub_id)] = num_of_intersections
level_dict = {}
for sub_id, level in levels:
if level not in level_dict:
level_dict[level] = []
level_dict[level].append(sub_id)
return conflict_dict, level_dict
def generate_schedule(level_dict, pattern):
schedule = []
level_queues = {level: iter(level_dict[level]) for level in pattern}
while any(level_queues.values()):
for level in pattern:
try:
schedule.append(next(level_queues[level]))
except StopIteration:
continue
return schedule
def calculate_cost(schedule, conflict_dict):
total_cost = 0
for day in range(len(schedule)):
for i, j in …
=> Ahmed Zakaria El-Refay

Task2/Moustafa mahmoud abd el azeem
import itertools
conflict_data = [
{"subject_id": 100, "conflict_subject_id": 200, "intersection_count": 30},
{"subject_id": 100, "conflict_subject_id": 300, "intersection_count": 15},
{"subject_id": 200, "conflict_subject_id": 300, "intersection_count": 20},
]
level_data = [
{"subject_id": 100, "level": 1},
{"subject_id": 200, "level": 2},
{"subject_id": 300, "level": 3},
]
level_to_subjects = {}
for item in level_data:
if item["level"] not in level_to_subjects:
level_to_subjects[item["level"]] = []
level_to_subjects[item["level"]].append(item["subject_id"])
level_patterns = [
[1, 2, 3],
[3, 2, 1],
]
def quick_sort_conflicts(conflicts):
if len(conflicts) <= 1:
return conflicts
pivot = conflicts[len(conflicts) // 2]
left = [x for x in conflicts if x["intersection_count"] < …
=>  Moustafa mahmoud abd el azeem

Task2/shahd samir abdelazim mohamed anbar
=> Create shahd samir abdelazim mohamed anbar

Task2/Mostafa Essam Elsayed.py
import itertools
def parse_input(conflicts, levels, subjects_per_level):
conflict_dict = {}
for sub_id, conflict_sub_id, num_of_intersections in conflicts:
conflict_dict[(sub_id, conflict_sub_id)] = num_of_intersections
level_dict = {}
for sub_id, level in levels:
if level not in level_dict:
level_dict[level] = []
level_dict[level].append(sub_id)
return conflict_dict, level_dict
def generate_schedule(level_dict, pattern):
schedule = []
level_queues = {level: iter(level_dict[level]) for level in pattern}
while any(level_queues.values()):
for level in pattern:
try:
schedule.append(next(level_queues[level]))
except StopIteration:
continue
return schedule
def calculate_cost(schedule, conflict_dict):
total_cost = 0
for day in range(len(schedule)):
for i, j in …
=> Create Mostafa Essam Elsayed.py
